### ISSUE TITLE
Uncaught ReferenceError: Then is not defined?

### ISSUE THREAD

**Issue by WayneVN** [stigmat4j/react-if-component#1]
index.js --->  var If
Then? Else?

**Comment by stigmat4j** [comment]
@WayneVN 
```js
var If = require('react-if-component');
```

Readme updated. Please use example.

**Comment by WayneVN** [comment]
@stigmat4j 
Why not retained 'Else' and 'Then'  ???

**Comment by stigmat4j** [comment]
@WayneVN, i was doing it for myself. Maybe later i'll make the support 'Then' and 'Else'.
